### ISSUE TITLE
EventType "javafx.event.EventType@26ca236"with parent "EVENT" already exists

### ISSUE THREAD

**Issue by alamenai** [slothsoft/example-gaugebar#1]
When i run main ,the program invokes this exception 

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at superfx.SuperFx.start(SuperFx.java:52)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	... 1 more
Caused by: java.lang.IllegalArgumentException: EventType "javafx.event.EventType@26ca236"with parent "EVENT" already exists
	at javafx.event.EventType.register(EventType.java:186)
	at javafx.event.EventType.<init>(EventType.java:128)
	at javafx.event.EventType.<init>(EventType.java:83)
	at superfxcustomcontrols.GaugeBar.<clinit>(GaugeBar.java:19)
	... 10 more
Exception running application superfx.SuperFx
Java Result: 1
```

**Comment by ghost** [comment]
I am having the same problem :(    Did you run this on Java 8 version?   EventType or Event class seemed obsolete or deprecated. I want to know what to use instead

**Comment by slothsoft** [comment]
I'm so sorry I took so long. I updated to Java 11 now. But the same fix (calling the constructor `EventType(EventType, String)` might have been necessary for Java 8, too.
